/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as PrototypingRouteImport } from './routes/prototyping'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as MoodboardRouteImport } from './routes/moodboard'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MemberRouteImport } from './routes/member'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypingRoute = PrototypingRouteImport.update({
  id: '/prototyping',
  path: '/prototyping',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodboardRoute = MoodboardRouteImport.update({
  id: '/moodboard',
  path: '/moodboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/members': typeof MembersRoute
  '/moodboard': typeof MoodboardRoute
  '/planning': typeof PlanningRoute
  '/prototyping': typeof PrototypingRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/members': typeof MembersRoute
  '/moodboard': typeof MoodboardRoute
  '/planning': typeof PlanningRoute
  '/prototyping': typeof PrototypingRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/members': typeof MembersRoute
  '/moodboard': typeof MoodboardRoute
  '/planning': typeof PlanningRoute
  '/prototyping': typeof PrototypingRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/member'
    | '/members'
    | '/moodboard'
    | '/planning'
    | '/prototyping'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/member'
    | '/members'
    | '/moodboard'
    | '/planning'
    | '/prototyping'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/member'
    | '/members'
    | '/moodboard'
    | '/planning'
    | '/prototyping'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRoute
  MembersRoute: typeof MembersRoute
  MoodboardRoute: typeof MoodboardRoute
  PlanningRoute: typeof PlanningRoute
  PrototypingRoute: typeof PrototypingRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototyping': {
      id: '/prototyping'
      path: '/prototyping'
      fullPath: '/prototyping'
      preLoaderRoute: typeof PrototypingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moodboard': {
      id: '/moodboard'
      path: '/moodboard'
      fullPath: '/moodboard'
      preLoaderRoute: typeof MoodboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRoute,
  MembersRoute: MembersRoute,
  MoodboardRoute: MoodboardRoute,
  PlanningRoute: PlanningRoute,
  PrototypingRoute: PrototypingRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
